export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const DEPARTMENTS_RECEIVED = 'DEPARTMENTS_RECEIVED';

export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';

export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';