export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';
export const DELETE_ALL_DEPARTMENTS = 'DELETE_ALL_DEPARTMENTS';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const DELETE_ALL_EMPLOYEES = 'DELETE_ALL_EMPLOYEES';

export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';